# Generated by Django 3.2.9 on 2021-12-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('name', models.TextField(max_length=45)),
                ('apellido1', models.TextField(max_length=45)),
                ('apellido2', models.TextField(max_length=45)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
