# Generated by Django 3.2.9 on 2021-12-13 00:22

import Cliente.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=45)),
                ('apellido1', models.TextField(max_length=45)),
                ('apellido2', models.TextField(max_length=45)),
                ('email', models.TextField()),
                ('telefono', models.IntegerField()),
                ('mensaje', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=45)),
                ('descripcion', models.TextField(max_length=255)),
                ('imagen', models.FileField(upload_to=Cliente.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto', models.BooleanField()),
                ('fecha', models.DateField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='idTipoProd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.tipoprod'),
        ),
    ]
