# Generated by Django 3.2.9 on 2021-11-25 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellido1', models.TextField()),
                ('apellido2', models.TextField()),
                ('email', models.TextField()),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto', models.BooleanField()),
                ('fecha', models.DateField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.producto')),
            ],
        ),
    ]
