# Generated by Django 3.2.9 on 2021-12-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_auto_20211213_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='mensaje',
            field=models.TextField(max_length=300),
        ),
    ]
